Tipo_Liquida=(
    ('UL', 'ULT. DIA DELMES'), #ULT. DIA DELMES
    ('PR', '1RO MES SIGUIENTE'), #1RO MES SIGUIENTE
    ('FA', 'FECHAS ALEATORIAS') #FECHAS ALEATORIAS
)

Modelo_liquida=(
    ('M', 'MENSUAL'), #MENSUAL
    ('F', 'RANGO DE FECHA') #RANGO DE FECHA
)

Tipo_Impuesto_coljuegos=(
    ('S', 'SOLO TARIFA FIJA'), #SOLO TARIFA FIJA
    ('S.V', 'SOLO TARIFA VARIABLE'), #SOLO TARIFA VARIABLE
    ('A.F.V', 'AMBAS FIJAS O VARIABLES')#AMBAS FIJAS O VARIABLES
)