from django.db import models
from Maestro.models import *
from ProcesosIGG.models import *
from Anexos.models import *
from .choices import *
from django.utils import timezone

# Create your models here.
class Liquidacione(models.Model):
    numero = models.CharField(max_length=10)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    id_cobro = models.IntegerField(default=0)
    id_mes = models.IntegerField(default=0)
    id_ano = models.IntegerField(default=0)
    fecha = models.DateTimeField()
    fecha_factura = models.DateTimeField()
    desde = models.DateTimeField(null=True, blank=True)
    hasta = models.DateTimeField(null=True, blank=True)
    id_status = models.CharField(max_length=50, default=0, choices=Status_Auditoria)
    dias = models.IntegerField(default=0)
    nro_maquinas = models.IntegerField(default=0)
    entrada = models.FloatField()
    salida = models.FloatField()
    premios = models.FloatField(default=0)
    jack_pot = models.FloatField(default=0)
    billeteros = models.FloatField()
    jugadas = models.FloatField()
    neto = models.FloatField()
    pay_back = models.FloatField(default=0)
    porcentaje = models.FloatField()
    impuesto = models.FloatField()
    iva = models.FloatField()
    otros = models.FloatField(default=0)
    monto = models.FloatField(default=0)
    monto_igg = models.FloatField(default=0)
    eliminar = models.IntegerField(default=0)
    descuentos = models.FloatField()
    monto_girar = models.FloatField(default=0)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True, verbose_name="Razon Social")
    impuesto_pendiente = models.FloatField(default=0)
    iva_pendiente = models.FloatField(default=0)
    otros_pendiente = models.FloatField(default=0)
    saldo_pendiente = models.FloatField(default=0)
    saldo_favor = models.FloatField(default=0)
    descuentos_pendiente = models.FloatField(default=0)
    fecha_email = models.DateTimeField(null=True, blank=True)
    pendiente = models.IntegerField(default=0)
    sin_transmitir = models.IntegerField(default=0)
    monto_sin_transmitir = models.FloatField(default=0)
    monto_soporte = models.FloatField(default=0)
    neto_mes = models.FloatField(default=0)
    ingreso = models.FloatField()
    ingreso_mes = models.FloatField()
    tipo = models.CharField(max_length=2, null=True, blank=True)
    dias_liquidar = models.IntegerField(default=0)
    desbalance = models.FloatField(default=0)
    suma_impuestos = models.FloatField(default=0)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

    def id_liquidacion(self):
        return  "{}".format(self.id)

    def __str__(self):
        return self.id_liquidacion()

class Notificacion(models.Model):
    numero = models.CharField(max_length=10)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True, blank=True)
    id_status = models.IntegerField(default=0, choices=Status_Auditoria)
    fecha = models.DateTimeField()
    asunto = models.CharField(max_length=50)
    texto = models.CharField(max_length=500)
    eliminar = models.IntegerField(default=0, null=True)
    fecha_notificacion = models.DateTimeField()

class Cargacsv(models.Model):
    message_id = models.TextField(max_length=50)
    venue_ho_id = models.IntegerField(default=0)
    bar_position = models.IntegerField(default=0)
    create_date = models.DateTimeField()
    transaction_date = models.DateTimeField()
    total_plays = models.FloatField(default=0)
    total_coin_in = models.FloatField(default=0)
    total_coin_out = models.FloatField(default=0)
    total_in = models.FloatField(default=0)
    total_out = models.FloatField(default=0)
    jackpot = models.FloatField(default=0)
    content_id = models.FloatField(default=0)

class CargaDiaria(models.Model):
    fecha = models.DateField()
    tipo = models.CharField(max_length=3, null=True)
    maquinasdb = models.FloatField(default=0)
    coinindb = models.FloatField(default=0)
    coinoutdb = models.FloatField(default=0)
    handpaydb = models.FloatField(default=0)
    jackpotdb = models.FloatField(default=0)
    billsdb = models.FloatField(default=0)
    playsdb = models.FloatField(default=0)
    netodb = models.FloatField(default=0)
    coinintxt = models.FloatField(default=0)
    coinoutxt = models.FloatField(default=0)
    handpaytxt = models.FloatField(default=0)
    jackpottxt = models.FloatField(default=0)
    billstxt = models.FloatField(default=0)
    playstxt = models.FloatField(default=0)
    netotxt = models.FloatField(default=0)
    maquinatxt = models.FloatField(default=0)
    eliminar = models.IntegerField(default=0, null=True)
    idrecord = models.BigIntegerField(default=0, null=True)
    lineasdb = models.FloatField(default=0)
    lineastxt = models.FloatField(default=0)
    fechacarga = models.DateField()
    metodo =  models.CharField(max_length=1, null=True)
    maquinames = models.FloatField(default=0)
    coininmes = models.FloatField(default=0)
    coinoutmes = models.FloatField(default=0)
    handpaymes = models.FloatField(default=0)
    jackpotmes = models.FloatField(default=0)
    billsmes = models.FloatField(default=0)
    playsmes = models.FloatField(default=0)
    netomes = models.FloatField(default=0)
    lineasmes = models.FloatField(default=0)
    archivo = models.CharField(max_length=50)
    idstatus = models.IntegerField(default=0)
    email = models.IntegerField(default=0)
    ingresodb = models.FloatField(default=0)
    ingresotxt = models.FloatField(default=0)
    ingresomes = models.FloatField(default=0)

class recaudodia (models.Model):
    salas = models.ForeignKey(Sala,  on_delete=models.CASCADE, null=True)
    maquina = models.ForeignKey(Maquina,  on_delete=models.CASCADE, null=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    liquidacion = models.IntegerField(default=0, null=True, blank=True)
    instalacion = models.ForeignKey(Instalacion, on_delete=models.CASCADE, null=True)
    fecha = models.DateField(auto_now_add=True)
    coinin = models.FloatField(default=0, null=True)
    coinout = models.FloatField(default=0, null=True)
    handpay = models.FloatField(default=0, null=True)
    jackpot = models.FloatField(default=0, null=True)
    bills = models.FloatField(default=0, null=True)
    plays = models.FloatField(default=0, null=True)
    neto = models.FloatField(default=0, null=True)
    payback = models.FloatField(default=0, null=True)
    fechacarga = models.DateField(auto_now_add=True, null=True)
    fechacarganew = models.DateField(auto_now_add=True, null=True)
    tipocarga = models.CharField(max_length=50, null=True, blank=True)
    eliminar = models.IntegerField(default=0, null=True, blank=True)
    id_seguridad = models.IntegerField(default=0, null=True, blank=True)
    fechaseguridad = models.DateField(auto_now_add=True, null=True)
    sincroniza = models.IntegerField(default=0, null=True, blank=True)
    fechasincroniza = models.DateField(auto_now_add=True, null=True)
    idrecord = models.IntegerField(default=0, null=True, blank=True)
    fechatotal = models.DateField(auto_now_add=True, null=True)
    web = models.IntegerField(default=0, null=True, blank=True)
    carga = models.IntegerField(default=0, null=True, blank=True)
    fechaextracto = models.DateField(auto_now_add=True, null=True)
    fechaultima = models.DateField(auto_now_add=True, null=True)
    ingreso = models.FloatField(default=0, null=True)
    id_inspired = models.CharField(max_length=15, null=True)
    id_posicion = models.IntegerField(default=0, null=True, blank=True)

class recaudomes (models.Model):
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    liquidacion = models.IntegerField(default=0, null=True, blank=True)
    coinin = models.FloatField(default=0, null=True)
    coinout = models.FloatField(default=0, null=True)
    handpay = models.FloatField(default=0, null=True)
    jackpot = models.FloatField(default=0, null=True)
    bills = models.FloatField(default=0, null=True)
    plays = models.FloatField(default=0, null=True)
    neto = models.FloatField(default=0, null=True)
    payback = models.FloatField(default=0, null=True)
    dias = models.IntegerField(default=0, null=True, blank=True)
    proyeccion = models.FloatField(default=0, null=True)
    ultimafecha = models.DateField(auto_now_add=True, null=True)
    ultimacargatra = models.CharField(max_length=1, null=True, blank=True)
    dia1 = models.CharField(max_length=1, null=True, blank=True)
    dia2 = models.CharField(max_length=1, null=True, blank=True)
    dia3 = models.CharField(max_length=1, null=True, blank=True)
    dia4 = models.CharField(max_length=1, null=True, blank=True)
    dia5 = models.CharField(max_length=1, null=True, blank=True)
    dia6 = models.CharField(max_length=1, null=True, blank=True)
    dia7 = models.CharField(max_length=1, null=True, blank=True)
    dia8 = models.CharField(max_length=1, null=True, blank=True)
    dia9 = models.CharField(max_length=1, null=True, blank=True)
    dia10 = models.CharField(max_length=1, null=True, blank=True)
    dia11 = models.CharField(max_length=1, null=True, blank=True)
    dia12 = models.CharField(max_length=1, null=True, blank=True)
    dia13 = models.CharField(max_length=1, null=True, blank=True)
    dia14 = models.CharField(max_length=1, null=True, blank=True)
    dia15 = models.CharField(max_length=1, null=True, blank=True)
    dia16 = models.CharField(max_length=1, null=True, blank=True)
    dia17 = models.CharField(max_length=1, null=True, blank=True)
    dia18 = models.CharField(max_length=1, null=True, blank=True)
    dia19 = models.CharField(max_length=1, null=True, blank=True)
    dia20 = models.CharField(max_length=1, null=True, blank=True)
    dia21 = models.CharField(max_length=1, null=True, blank=True)
    dia22 = models.CharField(max_length=1, null=True, blank=True)
    dia23 = models.CharField(max_length=1, null=True, blank=True)
    dia24 = models.CharField(max_length=1, null=True, blank=True)
    dia25 = models.CharField(max_length=1, null=True, blank=True)
    dia26 = models.CharField(max_length=1, null=True, blank=True)
    dia27 = models.CharField(max_length=1, null=True, blank=True)
    dia27 = models.CharField(max_length=1, null=True, blank=True)
    dia28 = models.CharField(max_length=1, null=True, blank=True)
    dia29 = models.CharField(max_length=1, null=True, blank=True)
    dia30 = models.CharField(max_length=1, null=True, blank=True)
    dia31 = models.CharField(max_length=1, null=True, blank=True)
    diasfestivos = models.IntegerField(default=0, null=True, blank=True)
    diasnoreporte = models.IntegerField(default=0, null=True, blank=True)
    diassinult = models.IntegerField(default=0, null=True, blank=True)
    ingreso = models.IntegerField(default=0, null=True, blank=True)
    ingresomes = models.IntegerField(default=0, null=True, blank=True)
    ingresodia = models.IntegerField(default=0, null=True, blank=True)
    idmes = models.IntegerField(default=0, null=True, blank=True)
    idano = models.IntegerField(default=0, null=True, blank=True)
    eliminar = models.IntegerField(default=0, null=True, blank=True)
    idseguridad = models.IntegerField(default=0, null=True, blank=True)
    fechaseguridad = models.DateField(auto_now_add=True, null=True)
    sincroniza = models.IntegerField(default=0, null=True, blank=True)
    fechasincroniza = models.DateField(auto_now_add=True, null=True)
    idrecord = models.IntegerField(default=0, null=True, blank=True)
    hold = models.FloatField(default=0, null=True)
    netomes = models.FloatField(default=0, null=True)
    coininmes = models.FloatField(default=0, null=True)
    coinoutmes = models.FloatField(default=0, null=True)
    handpaymes = models.FloatField(default=0, null=True)
    jackpotmes = models.FloatField(default=0, null=True)
    billsmes = models.FloatField(default=0, null=True)
    playsmes = models.FloatField(default=0, null=True)
    idinstalacion = models.IntegerField(default=0, null=True, blank=True)
    netodia = models.FloatField(default=0, null=True)
    diassin = models.IntegerField(default=0, null=True, blank=True)
    conectada = models.IntegerField(default=0, null=True, blank=True)
    promedioano = models.FloatField(default=0, null=True)
    proyeccionano = models.FloatField(default=0, null=True)
    instalacion = models.ForeignKey(Instalacion, on_delete=models.CASCADE, null=True)
    ultimacarga = models.CharField(max_length=50, null=True, blank=True)
    ultimafechatra = models.DateField(auto_now_add=True, null=True)


class liquidacionsala(models.Model):
    salas = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    idcobro = models.IntegerField(default=0, null=True, blank=True)
    liquidacion = models.ForeignKey(Liquidacione, on_delete=models.CASCADE, null=True)
    idmes = models.IntegerField(default=0, null=True, blank=True)
    idano = models.IntegerField(default=0, null=True, blank=True)
    idstatus = models.IntegerField(default=0, null=True, blank=True)
    nromaquina = models.IntegerField(default=0, null=True, blank=True)
    entrada = models.FloatField(default=0, null=True)
    salida = models.FloatField(default=0, null=True)
    premios = models.FloatField(default=0, null=True)
    jackpot = models.FloatField(default=0, null=True)
    billeteros = models.FloatField(default=0, null=True)
    jugadas = models.FloatField(default=0, null=True)
    neto = models.FloatField(default=0, null=True)
    payback = models.FloatField(default=0, null=True)
    porcentajes = models.FloatField(default=0, null=True)
    impuesto = models.FloatField(default=0, null=True)
    iva = models.FloatField(default=0, null=True)
    otros = models.FloatField(default=0, null=True)
    monto = models.FloatField(default=0, null=True)
    montoigg = models.FloatField(default=0, null=True)
    eliminar = models.IntegerField(default=0, null=True, blank=True)
    idseguridad = models.IntegerField(default=0, null=True, blank=True)
    fechaseguridad = models.DateField(auto_now_add=True, null=True)
    desde = models.DateField(auto_now_add=True, null=True)
    hasta = models.DateField(auto_now_add=True, null=True)
    idpcliente = models.IntegerField(default=0, null=True, blank=True)
    descuentos = models.FloatField(default=0, null=True)
    montogirar = models.FloatField(default=0, null=True)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True)
    impuestopedniente = models.FloatField(default=0, null=True)
    ivapendiente = models.FloatField(default=0, null=True)
    descuentospendientes = models.FloatField(default=0, null=True)
    pendiente = models.IntegerField(default=0, null=True, blank=True)
    sintrasnmitir = models.IntegerField(default=0, null=True, blank=True)
    montosintransmitir = models.FloatField(default=0, null=True)
    netomes = models.FloatField(default=0, null=True)
    ingreso = models.FloatField(default=0, null=True)
    ingresomes = models.FloatField(default=0, null=True)
    disliquidar = models.IntegerField(default=0, null=True, blank=True)

class liquidacionmaquina (models.Model):
    salas = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    liquidacion = models.ForeignKey(Liquidacione, on_delete=models.CASCADE, null=True)
    idcobro = models.IntegerField(default=0, null=True, blank=True)
    idmes = models.IntegerField(default=0, null=True, blank=True)
    idano = models.IntegerField(default=0, null=True, blank=True)
    idstatus = models.IntegerField(default=0, null=True, blank=True)
    entrada = models.FloatField(default=0, null=True)
    salida = models.FloatField(default=0, null=True)
    premios = models.FloatField(default=0, null=True)
    jackpot = models.FloatField(default=0, null=True)
    billeteros = models.FloatField(default=0, null=True)
    jugadas = models.FloatField(default=0, null=True)
    neto = models.FloatField(default=0, null=True)
    payback = models.FloatField(default=0, null=True)
    porcentajes = models.FloatField(default=0, null=True)
    impuesto = models.FloatField(default=0, null=True)
    iva = models.FloatField(default=0, null=True)
    otros = models.FloatField(default=0, null=True)
    monto = models.FloatField(default=0, null=True)
    montoigg = models.FloatField(default=0, null=True)
    eliminar = models.IntegerField(default=0, null=True, blank=True)
    idseguridad = models.IntegerField(default=0, null=True, blank=True)
    fechaseguridad = models.DateField(auto_now_add=True, null=True)
    desde = models.DateField(auto_now_add=True, null=True)
    hasta = models.DateField(auto_now_add=True, null=True)
    idpcliente = models.IntegerField(default=0, null=True, blank=True)
    idliquidacionsala = models.IntegerField(default=0, null=True, blank=True)
    instalacion = models.ForeignKey(Instalacion, on_delete=models.CASCADE, null=True)
    dias = models.IntegerField(default=0, null=True, blank=True)
    descuentos = models.FloatField(default=0, null=True)
    montogirar = models.FloatField(default=0, null=True)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True)
    diasreporte = models.IntegerField(default=0, null=True)
    incluir = models.IntegerField(default=0, null=True)
    diaspendiente = models.IntegerField(default=0, null=True)
    impuestopendiente = models.FloatField(default=0, null=True)
    ivpendiente = models.FloatField(default=0, null=True)
    otrospendiente = models.FloatField(default=0, null=True)
    descuentospendiente = models.FloatField(default=0, null=True)
    diassintransmitir = models.IntegerField(default=0, null=True)
    montosintransmitir =models.FloatField(default=0, null=True)
    montosoporte = models.FloatField(default=0, null=True)
    netomes = models.FloatField(default=0, null=True)
    ingreso = models.FloatField(default=0, null=True)
    ingresomes = models.FloatField(default=0, null=True)
    diasliquidar = models.IntegerField(default=0, null=True)

class DetalleLiquidacion(models.Model):
    liquidacion = models.ForeignKey(Liquidacione, on_delete=models.CASCADE, null=True, blank=True)
    maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE)
    neto_total = models.FloatField()
    impuesto_coljuegos = models.FloatField()
    valor_iva = models.FloatField()
    valor_a_descontar = models.FloatField()
    monto_a_dividir = models.FloatField()
    numero_registro = models.IntegerField(default=0, null=True)  # nuevocampo
    mes = models.CharField(max_length=15, null=True, blank=True)  # nuevocampo.
    anio = models.IntegerField(null=True, blank=True)  # nuevo campo para el año
    entrada_total = models.FloatField(default=0)
    salida_total = models.FloatField(default=0)
    bill_total = models.FloatField(default=0)
    play_total = models.FloatField(default=0)
    pago_cliente = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    pago_dueno = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    fecha = models.DateField(default=timezone.now)
