# Generated by Django 3.2.8 on 2022-08-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0002_alter_liquidacione_id_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargacsv',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='cargacsv',
            name='update_at',
        ),
    ]
