# Generated by Django 3.2.8 on 2022-08-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0015_auto_20220811_1336'),
        ('Auditoria', '0003_auto_20220812_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=3, null=True)),
                ('coinindb', models.FloatField(default=0)),
                ('coinoutdb', models.FloatField(default=0)),
                ('jackpotdb', models.FloatField(default=0)),
                ('billsdb', models.FloatField(default=0)),
                ('playsdb', models.FloatField(default=0)),
                ('netodb', models.FloatField(default=0)),
                ('coinintxt', models.FloatField(default=0)),
                ('coinoutxt', models.FloatField(default=0)),
                ('handpaydb', models.FloatField(default=0)),
                ('jackpottxt', models.FloatField(default=0)),
                ('billstxt', models.FloatField(default=0)),
                ('playstxt', models.FloatField(default=0)),
                ('netotxt', models.FloatField(default=0)),
                ('eliminar', models.IntegerField(default=0, null=True)),
                ('idrecord', models.BigIntegerField(default=0, null=True)),
                ('lineasdb', models.FloatField(default=0)),
                ('lineastxt', models.FloatField(default=0)),
                ('fechacarga', models.DateField()),
                ('metodo', models.CharField(max_length=1, null=True)),
                ('maquinames', models.FloatField(default=0)),
                ('coininmes', models.FloatField(default=0)),
                ('coinoutmes', models.FloatField(default=0)),
                ('handpaymes', models.FloatField(default=0)),
                ('jackpotmes', models.FloatField(default=0)),
                ('billsmes', models.FloatField(default=0)),
                ('playsmes', models.FloatField(default=0)),
                ('netomes', models.FloatField(default=0)),
                ('lineasmes', models.FloatField(default=0)),
                ('archivo', models.CharField(max_length=50)),
                ('idstatus', models.IntegerField(default=0)),
                ('email', models.IntegerField(default=0)),
                ('ingresodb', models.FloatField(default=0)),
                ('ingresotxt', models.FloatField(default=0)),
                ('ingresomes', models.FloatField(default=0)),
                ('maquinas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
            ],
        ),
    ]
