# Generated by Django 3.2.8 on 2022-09-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0008_auto_20220525_0954'),
        ('Auditoria', '0004_cargadiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargadiaria',
            name='id_inspired',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cargadiaria',
            name='id_posicion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cargadiaria',
            name='instalacion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.instalacion'),
        ),
    ]
