# Generated by Django 3.2.8 on 2022-09-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0005_auto_20220915_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargadiaria',
            old_name='instalacion_id',
            new_name='instalacion',
        ),
    ]
