# Generated by Django 3.2.8 on 2022-09-16 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0008_auto_20220525_0954'),
        ('Maestro', '0015_auto_20220811_1336'),
        ('Auditoria', '0006_rename_instalacion_id_cargadiaria_instalacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargadiaria',
            name='id_inspired',
        ),
        migrations.RemoveField(
            model_name='cargadiaria',
            name='id_posicion',
        ),
        migrations.RemoveField(
            model_name='cargadiaria',
            name='instalacion',
        ),
        migrations.CreateModel(
            name='recaudodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('coinin', models.FloatField(default=0)),
                ('coinout', models.FloatField(default=0)),
                ('handpay', models.FloatField(default=0)),
                ('jackpot', models.FloatField(default=0)),
                ('bills', models.FloatField(default=0)),
                ('plays', models.FloatField(default=0)),
                ('neto', models.FloatField(default=0)),
                ('payback', models.FloatField(default=0)),
                ('coininnew', models.FloatField(default=0)),
                ('coinoutnew', models.FloatField(default=0)),
                ('handpaynew', models.FloatField(default=0)),
                ('jackpotnew', models.FloatField(default=0)),
                ('billsnew', models.FloatField(default=0)),
                ('playsnew', models.FloatField(default=0)),
                ('netonew', models.FloatField(default=0)),
                ('paybacknew', models.FloatField(default=0)),
                ('coininold', models.FloatField(default=0)),
                ('coinoutold', models.FloatField(default=0)),
                ('handpayold', models.FloatField(default=0)),
                ('jackpotold', models.FloatField(default=0)),
                ('billsold', models.FloatField(default=0)),
                ('playsold', models.FloatField(default=0)),
                ('netoold', models.FloatField(default=0)),
                ('paybackold', models.FloatField(default=0)),
                ('fechacarga', models.DateField()),
                ('fechacarganew', models.DateField()),
                ('tipocarga', models.DateField()),
                ('eliminar', models.IntegerField(blank=True, default=0, null=True)),
                ('id_seguridad', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaseguridad', models.DateField()),
                ('sincroniza', models.IntegerField(blank=True, default=0, null=True)),
                ('fechasincroniza', models.DateField()),
                ('idrecord', models.IntegerField(blank=True, default=0, null=True)),
                ('fechatotal', models.DateField()),
                ('web', models.IntegerField(blank=True, default=0, null=True)),
                ('carga', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaextracto', models.DateField()),
                ('fechaultima', models.DateField()),
                ('ingreso', models.FloatField(default=0)),
                ('id_inspired', models.CharField(max_length=15)),
                ('id_posicion', models.IntegerField(blank=True, default=0, null=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('instalacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.instalacion')),
                ('liquidacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auditoria.liquidacione')),
                ('maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
            ],
        ),
    ]
