# Generated by Django 3.2.8 on 2022-09-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0008_auto_20220929_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudodia',
            name='bills',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='coinin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='coinout',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechacarga',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechacarganew',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechaextracto',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechaseguridad',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechasincroniza',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechatotal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='fechaultima',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='handpay',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='ingreso',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='jackpot',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='neto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='payback',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='plays',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='tipocarga',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
