# Generated by Django 3.2.8 on 2022-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0009_auto_20220929_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recaudodia',
            old_name='sala',
            new_name='salas',
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='id_inspired',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
