# Generated by Django 3.2.8 on 2022-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0010_auto_20221018_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudodia',
            name='instalacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
