# Generated by Django 3.2.8 on 2022-10-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0009_alter_instalacion_tipooperacion'),
        ('Auditoria', '0011_alter_recaudodia_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudodia',
            name='instalacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.instalacion'),
        ),
        migrations.AlterField(
            model_name='recaudodia',
            name='liquidacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
