# Generated by Django 3.2.8 on 2022-10-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0012_auto_20221018_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudodia',
            name='tipocarga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
