# Generated by Django 4.1.2 on 2022-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0013_alter_recaudodia_tipocarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargadiaria',
            name='maquinas',
        ),
        migrations.AddField(
            model_name='cargadiaria',
            name='maquinasdb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cargadiaria',
            name='maquinatxt',
            field=models.FloatField(default=0),
        ),
    ]
