# Generated by Django 4.1.2 on 2022-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0014_remove_cargadiaria_maquinas_cargadiaria_maquinasdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargadiaria',
            name='handpaytxt',
            field=models.FloatField(default=0),
        ),
    ]
