# Generated by Django 4.1.2 on 2022-10-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0015_cargadiaria_handpaytxt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargadiaria',
            name='handpaytxt',
        ),
    ]
