# Generated by Django 4.1.2 on 2022-10-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0018_remove_cargadiaria_handpaytxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargadiaria',
            name='handpaytxt',
            field=models.FloatField(default=0),
        ),
    ]
