# Generated by Django 4.1.6 on 2023-06-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0039_alter_sala_modelo'),
        ('Auditoria', '0019_cargadiaria_handpaytxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='recaudomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidacion', models.IntegerField(blank=True, default=0, null=True)),
                ('coinin', models.FloatField(default=0, null=True)),
                ('coinout', models.FloatField(default=0, null=True)),
                ('handpay', models.FloatField(default=0, null=True)),
                ('jackpot', models.FloatField(default=0, null=True)),
                ('bills', models.FloatField(default=0, null=True)),
                ('plays', models.FloatField(default=0, null=True)),
                ('neto', models.FloatField(default=0, null=True)),
                ('payback', models.FloatField(default=0, null=True)),
                ('dias', models.IntegerField(blank=True, default=0, null=True)),
                ('proyeccion', models.FloatField(default=0, null=True)),
                ('ultimafecha', models.DateField(auto_now_add=True, null=True)),
                ('ultimacargatra', models.CharField(blank=True, max_length=1, null=True)),
                ('dia1', models.CharField(blank=True, max_length=1, null=True)),
                ('dia2', models.CharField(blank=True, max_length=1, null=True)),
                ('dia3', models.CharField(blank=True, max_length=1, null=True)),
                ('dia4', models.CharField(blank=True, max_length=1, null=True)),
                ('dia5', models.CharField(blank=True, max_length=1, null=True)),
                ('dia6', models.CharField(blank=True, max_length=1, null=True)),
                ('dia7', models.CharField(blank=True, max_length=1, null=True)),
                ('dia8', models.CharField(blank=True, max_length=1, null=True)),
                ('dia9', models.CharField(blank=True, max_length=1, null=True)),
                ('dia10', models.CharField(blank=True, max_length=1, null=True)),
                ('dia11', models.CharField(blank=True, max_length=1, null=True)),
                ('dia12', models.CharField(blank=True, max_length=1, null=True)),
                ('dia13', models.CharField(blank=True, max_length=1, null=True)),
                ('dia14', models.CharField(blank=True, max_length=1, null=True)),
                ('dia15', models.CharField(blank=True, max_length=1, null=True)),
                ('dia16', models.CharField(blank=True, max_length=1, null=True)),
                ('dia17', models.CharField(blank=True, max_length=1, null=True)),
                ('dia18', models.CharField(blank=True, max_length=1, null=True)),
                ('dia19', models.CharField(blank=True, max_length=1, null=True)),
                ('dia20', models.CharField(blank=True, max_length=1, null=True)),
                ('dia21', models.CharField(blank=True, max_length=1, null=True)),
                ('dia22', models.CharField(blank=True, max_length=1, null=True)),
                ('dia23', models.CharField(blank=True, max_length=1, null=True)),
                ('dia24', models.CharField(blank=True, max_length=1, null=True)),
                ('dia25', models.CharField(blank=True, max_length=1, null=True)),
                ('dia26', models.CharField(blank=True, max_length=1, null=True)),
                ('dia27', models.CharField(blank=True, max_length=1, null=True)),
                ('dia28', models.CharField(blank=True, max_length=1, null=True)),
                ('dia29', models.CharField(blank=True, max_length=1, null=True)),
                ('dia30', models.CharField(blank=True, max_length=1, null=True)),
                ('dia31', models.CharField(blank=True, max_length=1, null=True)),
                ('diasfestivos', models.IntegerField(blank=True, default=0, null=True)),
                ('diasnoreporte', models.IntegerField(blank=True, default=0, null=True)),
                ('diassinult', models.IntegerField(blank=True, default=0, null=True)),
                ('ingreso', models.IntegerField(blank=True, default=0, null=True)),
                ('ingresomes', models.IntegerField(blank=True, default=0, null=True)),
                ('ingresodia', models.IntegerField(blank=True, default=0, null=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
            ],
        ),
    ]
