# Generated by Django 4.1.6 on 2023-06-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0020_recaudomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudomes',
            name='billsmes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='coininmes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='coinoutmes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='conectada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='diassin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='fechaseguridad',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='fechasincroniza',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='handpaymes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='hold',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='idano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='idinstalacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='idmes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='idrecord',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='idseguridad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='jackpotmes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='netodia',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='netomes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='playsmes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='promedioano',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='proyeccionano',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='sincroniza',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
