# Generated by Django 4.1.6 on 2023-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0021_recaudomes_billsmes_recaudomes_coininmes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudodia',
            name='instalacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
