# Generated by Django 4.1.6 on 2023-06-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0018_instalacion_dialiquida'),
        ('Auditoria', '0023_alter_recaudodia_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudomes',
            name='instalacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.instalacion'),
        ),
    ]
