# Generated by Django 4.1.6 on 2023-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0025_liquidacionsala_liquidacionmaquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudomes',
            name='ultimacarga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recaudomes',
            name='ultimafechatra',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
