# Generated by Django 4.2.4 on 2025-05-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0047_anoeconomico'),
        ('Auditoria', '0026_recaudomes_ultimacarga_recaudomes_ultimafechatra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neto_total', models.FloatField()),
                ('impuesto_coljuegos', models.FloatField()),
                ('valor_iva', models.FloatField()),
                ('valor_a_descontar', models.FloatField()),
                ('monto_a_dividir', models.FloatField()),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Auditoria.liquidacione')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
            ],
        ),
    ]
