# Generated by Django 4.2.4 on 2025-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0027_detalleliquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacione',
            name='desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
