# Generated by Django 4.2.4 on 2025-05-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0028_alter_liquidacione_desde_alter_liquidacione_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auditoria.liquidacione'),
        ),
    ]
