# Generated by Django 4.2.4 on 2025-05-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0029_alter_detalleliquidacion_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='mes',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='detalleliquidacion',
            name='numero_registro',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
