# Generated by Django 4.2.4 on 2025-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0030_detalleliquidacion_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='bill_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleliquidacion',
            name='entrada_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleliquidacion',
            name='play_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleliquidacion',
            name='salida_total',
            field=models.FloatField(default=0),
        ),
    ]
