# Generated by Django 4.2.4 on 2025-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0031_detalleliquidacion_bill_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacione',
            name='descuentos_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='fecha_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='impuesto_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='iva_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='jack_pot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='monto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='monto_girar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='monto_igg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='monto_sin_transmitir',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='monto_soporte',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='neto_mes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='otros',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='otros_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='pay_back',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='premios',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='saldo_favor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='saldo_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacione',
            name='tipo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
