# Generated by Django 4.2.4 on 2025-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0032_alter_liquidacione_descuentos_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
