# Generated by Django 4.2.4 on 2025-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0033_detalleliquidacion_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='pago_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleliquidacion',
            name='pago_dueno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
