# Generated by Django 4.2.4 on 2025-06-13 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0034_detalleliquidacion_pago_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
