from django.db import models
from .choices import *
from Anexos.models import *
from Maestro.models import *

# Create your models here.
class Contrato(models.Model):
    id_status = models.IntegerField(choices=Status_Contrato)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True, blank=True)
    clase = models.CharField(max_length=2, choices=Clase)
    tipo = models.CharField(max_length=2, choices=Tipo)
    contacto = models.CharField(max_length=50)
    fecha = models.DateTimeField()
    fecha_contrato = models.DateTimeField()
    fecha_instalacion = models.DateTimeField()
    fecha_inicio = models.DateTimeField()
    observacion = models.CharField(max_length=100)
    eliminar = models.IntegerField(default=0)
    cantidad = models.IntegerField(default=0)
    responsable = models.CharField(max_length=50)
    modelo = models.CharField(max_length=80, choices=Modelo_ProcesoIGG)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

    def Contratos(self):
        return  "{}".format(self.id)

    def __str__(self):
        return self.Contratos()

class Asignacione(models.Model):
    #numero = models.CharField(max_length=10, auto_created=True, null=True)
    #id_status = models.CharField(max_length=100, choices=Status_Asignacion)
    stado = models.ForeignKey(StatusAsignacion, on_delete=models.CASCADE, null=True, verbose_name="Estado")
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    fecha = models.DateField(verbose_name="Fecha Registro")
    fecha_asignacion = models.DateField()
    contacto = models.CharField(max_length=50)
    observacion = models.CharField(max_length=100, blank=True)
    eliminar = models.IntegerField(default=0, blank=True)
    cantidad = models.IntegerField(default=0, blank=True)
    fecha_codigos = models.DateField(auto_now_add=True)
    #fecha_despachos = models.DateTimeField(default=0)
    fecha_instalacion = models.DateField(auto_now_add=True, null=True, blank=True)
    #transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True, blank=True)
    tecnico = models.ForeignKey(Tecnico, on_delete=models.CASCADE, null=True, blank=True)
    notificacion = models.IntegerField(default=0, blank=True)
    fecha_notificacion = models.DateField(auto_now_add=True, null=True, blank=True)
    ums_responsable = models.CharField(max_length=50, blank=True)
    internet = models.IntegerField(default=0, blank=True)
    revisado = models.CharField(max_length=50, blank=True)
    fecha_revisado = models.DateField(null=True, auto_now_add=True, blank=True)
    contrato = models.ForeignKey(Contrato, on_delete=models.CASCADE, null=True, blank=True)
    modelo = models.CharField(max_length=100, choices=Modelo_ProcesoIGG,null=True, blank=True)
    operacion = models.ForeignKey(Status,  on_delete=models.CASCADE, null=True)
    numero_seriales = models.IntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")
    fecha_despacho = models.DateField(auto_now_add=True, blank = True, null=True)
    contacto = models.CharField(max_length=50)
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True, blank=True)
    direccion = models.CharField(max_length=100, blank=True)
    conductor = models.CharField(max_length=50, blank=True)
    placa = models.CharField(max_length=10, blank=True)
    guia = models.CharField(max_length=30, blank=True)

    def id_asignacion(self):
        return  "{}".format(self.id)

    def __str__(self):
        return self.id_asignacion()

class Despacho(models.Model):
    numero = models.CharField(max_length=10)
    id_status = models.IntegerField(default=50, choices=Status_Despacho)
    id_ano = models.IntegerField(default=0)
    id_cliente = models.IntegerField(default=0)
    fecha = models.DateTimeField()
    fecha_despacho = models.DateTimeField()
    contacto = models.CharField(max_length=50)
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True, blank=True)
    direccion = models.CharField(max_length=100)
    conductor = models.CharField(max_length=50)
    placa = models.CharField(max_length=10)
    guia = models.CharField(max_length=30)
    observacion = models.CharField(max_length=100)
    eliminar = models.IntegerField(default=0)
    id_seguridad = models.IntegerField(default=0)
    fecha_seguridad = models.DateTimeField()
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

    def id_despacho(self):
        return  "{}".format(self.id)

    def __str__(self):
        return self.id_despacho()

class Instalacion(models.Model):
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    salas = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    maquinas = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True)
    id_inspired = models.IntegerField(default=0, null=True)
    id_posicion = models.IntegerField(default=0, null=True)
    fecha_instalacion = models.DateField()
    fecha_retiro = models.DateField(null=True, blank=True)
    status = models.ForeignKey(statusinstalacion, on_delete=models.CASCADE, null=True)
    coin_in = models.FloatField(default=0)
    coin_out = models.FloatField(default=0)
    handpay = models.FloatField(default=0)
    jackpot = models.FloatField(default=0)
    bills = models.FloatField(default=0)
    plays = models.FloatField(default=0)
    neto = models.FloatField(default=0)
    hold = models.FloatField(default=0)
    payback = models.FloatField(default=0)
    eliminar = models.IntegerField(default=0, blank=True)
    porcentaje = models.FloatField(default=0)
    impuesto = models.FloatField(default=0)
    iva = models.FloatField(default=0)
    otros = models.FloatField(default=0)
    descuentos = models.FloatField(default=0)
    dias_liquida = models.IntegerField(default=30, null=True)
    fechaliquida = models.DateField()
    tipoliquida = models.CharField(max_length=2)
    liquida = models.IntegerField(default=0)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True)
    horaliquida = models.IntegerField(default=0)
    menumix = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True)
    variable = models.FloatField(default=0)
    cobrodia = models.FloatField(default=0)
    presupuestodia = models.FloatField(default=0)
    cobrosoporte = models.FloatField(default=0)
    montosoporte = models.FloatField(default=0)
    dialiquida = models.CharField(max_length=2, null=True)
    #idmonedasoporte =
    tarifa = models.CharField(max_length=2)
    tipooperacion = models.CharField(max_length=2, null=True)
    nuc = models.CharField(max_length=15, null=True)
    numeroresolucion = models.CharField(max_length=15, null=True)
    repcoljuegos = models.CharField(max_length=15, null=True)
    produccionigg = models.CharField(max_length=15, null=True)
    id_modelo_igg = models.ForeignKey(Modelo, on_delete=models.CASCADE, null=True, blank=True)
    ingreso = models.FloatField(default=0)
    tipocoljuegos = models.CharField(max_length=15, null=True)
    id_status = models.CharField(max_length=15, null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

    def id_instalacion(self):
        return  "{}".format(self.id)

    def __str__(self):
        return self.id_instalacion()

class Retiro(models.Model):
    numero = models.CharField(max_length=10, blank=True)
    id_status = models.ForeignKey(statusretiro, on_delete=models.CASCADE, null=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    fecha = models.IntegerField(default=0, blank=True)
    fecha_retiro = models.DateField()
    fecha_traslado = models.CharField(max_length=10, blank=True, null=True)
    cantidad = models.IntegerField(default=0, blank=True)
    conductor = models.CharField(max_length=50, blank=True)
    placa = models.CharField(max_length=10, blank=True)
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True, blank=True)
    guia = models.CharField(max_length=30, blank=True)
    observacion = models.CharField(max_length=100, blank=True)
    tipo = models.CharField(max_length=2, blank=True)
    eliminar = models.IntegerField(default=0, blank=True)
    contacto = models.CharField(max_length=50, blank=True)
    fecha_recibido = models.CharField(max_length=10, blank=True)
    recibido = models.CharField(max_length=50, blank=True)
    notificacion = models.IntegerField(default=0, blank=True)
    fecha_notificacion = models.CharField(max_length=10, blank=True)
    ums_responsable = models.CharField(max_length=50, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

class Seriales(models.Model):
    id_inventario = models.IntegerField(blank=True)
    id_entrega = models.IntegerField(blank=True)
    id_produccion = models.IntegerField(blank=True)
    id_maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True, blank=True)
    id_asignacion = models.ForeignKey(Asignacione, on_delete=models.CASCADE, null=True, blank=True)
    id_despacho = models.ForeignKey(Despacho, on_delete=models.CASCADE, null=True, blank=True)
    id_status = models.IntegerField(blank=True)
    serie_pmv = models.IntegerField(default=0)
    serie_igg = models.CharField(max_length=20, blank=True)
    fecha = models.DateField(default=0, verbose_name="fecha asignacion")
    fecha_entrega = models.DateField(auto_now_add=True)
    fecha_produccion = models.DateField(auto_now_add=True)
    eliminar = models.IntegerField(default=0, blank=True)
    ids_eguridad = models.IntegerField(default=0, blank=True)
    fecha_seguridad = models.DateField(auto_now_add=True)
    fecha_despacho = models.DateField(auto_now_add=True)
    fecha_operacion = models.DateField(auto_now_add=True)
    fecha_asignacion = models.DateField(default=0)
    ide_ntrega_serial = models.IntegerField(blank=True)
    fecha_codigos = models.DateField(auto_now_add=True)
    id_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    id_sala = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True, blank=True)
    id_retiro = models.IntegerField(default=0, blank=True)
    fecha_retiro = models.DateField(auto_now_add=True)
    factura_pmv = models.CharField(max_length=20, blank=True)

class MovRetiros(models.Model):
    retiro = models.ForeignKey(Retiro, on_delete=models.CASCADE, related_name='movimientos')
    maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE)
    cantidad_retirada = models.PositiveIntegerField(default=1)
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    ums = models.CharField(max_length=3, default=0, blank=True, null=True)
    fecha = models.CharField(max_length=10, null=True)
    igg = models.IntegerField(default=0, null=True, blank=True)
    posicion = models.IntegerField(default=0, null=True, blank=True)

