# Generated by Django 3.2.8 on 2022-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0004_auto_20220309_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='liquida',
            field=models.CharField(choices=[('UL', 'UL'), ('MS', 'MS'), ('FA', 'FA')], default='ULT. DIA DELMES', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='liquida_mes',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='MENSUAL', max_length=50, null=True, verbose_name='Metodo'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id_tipo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=20, null=True, verbose_name='Metodo:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='liquida',
            field=models.CharField(choices=[('UL', 'UL'), ('MS', 'MS'), ('FA', 'FA')], max_length=20, null=True, verbose_name='Cierre Liquidacion:'),
        ),
    ]
