# Generated by Django 3.2.8 on 2022-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0005_auto_20220516_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_liquida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hora_liquida',
            field=models.DateField(default=0, null=True),
        ),
    ]
