# Generated by Django 3.2.8 on 2022-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0006_auto_20220531_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_seguridad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
