# Generated by Django 3.2.8 on 2022-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0007_alter_cliente_fecha_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cobro_dia',
            field=models.IntegerField(null=True, verbose_name='Cobro x Días NO Transm.:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condicion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dias_sin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días Sin Transmitir:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EMail:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_contadores',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='EMail Contadores:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_fallas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='EMail Fallas:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_recaudo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EMail Rec. x Maquina:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_recaudo_grupo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_recaudo_sala',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_sin_transmitir_dia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_sin_transmmitir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='EMail Sin Transmitir:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fallas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_seguridad',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_sincroniza',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hora_liquida',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='liquida',
            field=models.CharField(choices=[('ULT. DIA DELMES', 'ULT. DIA DELMES'), ('1RO MES SIGUIENTE', '1RO MES SIGUIENTE'), ('FECHAS ALEATORIAS', 'FECHAS ALEATORIAS')], default='ULT. DIA DELMES', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='liquida_mes',
            field=models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('RANGO DE FECHA', 'RANGO DE FECHA')], default='MENSUAL', max_length=50, null=True, verbose_name='Metodo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='porcentaje',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='% Participación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='visor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Incluir en el visor'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id_tipo',
            field=models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('RANGO DE FECHA', 'RANGO DE FECHA')], max_length=20, null=True, verbose_name='Metodo:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='liquida',
            field=models.CharField(choices=[('ULT. DIA DELMES', 'ULT. DIA DELMES'), ('1RO MES SIGUIENTE', '1RO MES SIGUIENTE'), ('FECHAS ALEATORIAS', 'FECHAS ALEATORIAS')], max_length=20, null=True, verbose_name='Cierre Liquidacion:'),
        ),
    ]
