# Generated by Django 3.2.8 on 2022-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0008_auto_20220601_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='email sin transmitir'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contadores texto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_liquida',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='variable',
            field=models.FloatField(default=12.0, null=True, verbose_name='% Variable:'),
        ),
    ]
