# Generated by Django 3.2.8 on 2022-06-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0009_auto_20220606_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='hora_liquida',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
