# Generated by Django 3.2.8 on 2022-06-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0010_alter_sala_hora_liquida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fallas',
            new_name='emeailrecmaquina',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='porcentaje',
            field=models.FloatField(default=0.0, null=True, verbose_name='% Participación'),
        ),
    ]
