# Generated by Django 3.2.8 on 2022-06-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0011_auto_20220621_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='emeailrecmaquina',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
