# Generated by Django 3.2.8 on 2022-08-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0012_alter_cliente_emeailrecmaquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fallas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fallas'),
        ),
    ]
