# Generated by Django 3.2.8 on 2022-08-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0013_cliente_fallas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='clientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fechaFrozen',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_actualiza',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_cobro',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_despacho',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_garantia',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_instalacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_liquidacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_produccion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_retiro',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_seguridad',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_soporte',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='id_inspired',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='id_posicion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='salas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala'),
        ),
    ]
