# Generated by Django 3.2.8 on 2022-08-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0007_auto_20220801_2215'),
        ('Maestro', '0014_auto_20220804_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='razon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social', verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='reservacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
