# Generated by Django 3.2.8 on 2022-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0015_auto_20220811_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='liquida',
            field=models.CharField(choices=[('UL', 'ULT. DIA DELMES'), ('PR', '1RO MES SIGUIENTE'), ('FA', 'FECHAS ALEATORIAS')], default='ULT. DIA DELMES', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='liquida_mes',
            field=models.CharField(choices=[('M', 'MENSUAL'), ('F', 'RANGO DE FECHA')], default='MENSUAL', max_length=50, null=True, verbose_name='Metodo'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id_tipo',
            field=models.CharField(choices=[('M', 'MENSUAL'), ('F', 'RANGO DE FECHA')], max_length=20, null=True, verbose_name='Metodo:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='liquida',
            field=models.CharField(choices=[('UL', 'ULT. DIA DELMES'), ('PR', '1RO MES SIGUIENTE'), ('FA', 'FECHAS ALEATORIAS')], max_length=20, null=True, verbose_name='Cierre Liquidacion:'),
        ),
    ]
