# Generated by Django 3.2.8 on 2022-09-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0016_auto_20220929_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email2',
            new_name='email_fallas_sala',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email4',
            new_name='email_rec_grupo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email3',
            new_name='email_rec_sala',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email_5',
            new_name='email_sin_transmmitir_text',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_6',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_sin_transmitir_dia',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_contadores',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contadores texto'),
        ),
    ]
