# Generated by Django 3.2.8 on 2022-09-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0017_auto_20220930_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_contadores_select',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='EMail Contadores:'),
        ),
    ]
