# Generated by Django 3.2.8 on 2022-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0018_cliente_email_contadores_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='porcentaje',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10, null=True, verbose_name='% Participación'),
        ),
    ]
