# Generated by Django 3.2.8 on 2022-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0019_alter_cliente_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='porcentaje',
            field=models.IntegerField(default=0.0, null=True, verbose_name='% Participación'),
        ),
    ]
