# Generated by Django 3.2.8 on 2022-10-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0020_alter_cliente_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='porcentaje',
            field=models.FloatField(default=0, null=True, verbose_name='% Participación'),
        ),
    ]
