# Generated by Django 3.2.8 on 2022-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0021_alter_cliente_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipoparticipacion',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
    ]
