# Generated by Django 3.2.8 on 2022-10-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0022_cliente_tipoparticipacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipoactualizacion',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipogarantiahadware',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiposoporteremoto',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
    ]
