# Generated by Django 3.2.8 on 2022-10-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0023_auto_20221012_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipoactualizacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipogarantiahadware',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipoparticipacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tiposoporteremoto',
        ),
    ]
