# Generated by Django 3.2.8 on 2022-10-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0024_auto_20221012_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tipoactualizacion',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipogarantiahadware',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipoparticipacion',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tiposoporteremoto',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
    ]
