# Generated by Django 3.2.8 on 2022-10-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0025_auto_20221012_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fechavenceliquidacion',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
