# Generated by Django 3.2.8 on 2022-10-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0026_maquina_fechavenceliquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fechavenceactualizacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='fechavencegarantia',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='fechavencesoporte',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
