# Generated by Django 3.2.8 on 2022-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0028_alter_maquina_modeloigg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='modeloIGG',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
