# Generated by Django 3.2.8 on 2022-10-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0008_tipomaquina'),
        ('Maestro', '0029_alter_maquina_modeloigg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='modeloIGG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tipomaquina'),
        ),
    ]
