# Generated by Django 3.2.8 on 2022-10-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0008_tipomaquina'),
        ('Maestro', '0030_alter_maquina_modeloigg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='id_tipo_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tipomaquina', verbose_name='Tipo Maquina:'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='modeloIGG',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
