# Generated by Django 3.2.8 on 2022-10-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0031_auto_20221014_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='fechavenceactualizacion',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='fechavencegarantia',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='fechavencesoporte',
        ),
        migrations.AddField(
            model_name='maquina',
            name='numeroresolucion',
            field=models.CharField(blank=True, default=0, max_length=25),
        ),
    ]
