# Generated by Django 3.2.8 on 2022-10-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0032_auto_20221014_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='tipoactualizacion',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='tipogarantiahadware',
        ),
        migrations.AddField(
            model_name='maquina',
            name='sin_transmitir',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
