# Generated by Django 4.1.2 on 2022-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0033_auto_20221014_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tipo_operacion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipoparticipacion',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tiposoporteremoto',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
