# Generated by Django 4.1.2 on 2023-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0034_alter_maquina_tipo_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='liquida',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
