# Generated by Django 4.1.2 on 2023-01-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0011_modeloliquidacion'),
        ('Maestro', '0035_alter_cliente_liquida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='liquida_mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.modeloliquidacion', verbose_name='Modelo'),
        ),
    ]
