# Generated by Django 4.1.2 on 2023-01-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0011_modeloliquidacion'),
        ('Maestro', '0036_alter_cliente_liquida_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='id_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tiposala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo_liquida',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiene Liq. / Cobro Fijo:'),
        ),
    ]
