# Generated by Django 4.1.2 on 2023-01-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0011_modeloliquidacion'),
        ('Maestro', '0037_alter_sala_id_tipo_alter_sala_tipo_liquida'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.modeloliquidacion', verbose_name='Modelo'),
        ),
    ]
