# Generated by Django 4.1.6 on 2023-02-07 15:12

from django.db import migrations, models
import django.db.models.deletion
import django

class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0011_modeloliquidacion'),
        ('Maestro', '0038_sala_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.modeloliquidacion', verbose_name='Modelo'),
        ),
    ]
