# Generated by Django 4.2.4 on 2024-02-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0039_alter_sala_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contratoCol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
