# Generated by Django 4.2.4 on 2024-04-16 13:50

from django.db import migrations, models
import django.db.models.deletion
import django

class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0018_alter_razos_social_create_at_and_more'),
        ('Maestro', '0040_alter_cliente_contratocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
