# Generated by Django 4.2.4 on 2024-04-16 14:48

from django.db import migrations, models
import django

class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0041_alter_cliente_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
    ]
