# Generated by Django 4.2.4 on 2024-04-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0042_alter_cliente_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='razon',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='Anexos.razos_social'),
        ),
    ]
