# Generated by Django 4.2.4 on 2024-04-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0018_alter_razos_social_create_at_and_more'),
        ('Maestro', '0043_auto_20240416_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='razon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
    ]
