# Generated by Django 4.2.4 on 2024-04-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('Anexos', '0020_alter_razos_social_ciudad_cedula'),
        ('Maestro', '0044_alter_maquina_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='razon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
    ]
