# Generated by Django 4.2.4 on 2024-07-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0045_alter_maquina_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tipooperacion'),
        ),
    ]
