# Generated by Django 4.2.4 on 2025-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0046_alter_maquina_id_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año Económico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tarifa_fija_0_500', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Fija ColJuegos x Apuesta $0 - $500')),
                ('tarifa_fija_mas_500', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Fija ColJuegos x Apuesta > $500')),
                ('tarifa_fija_progresiva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Fija ColJuegos x Apuesta Progresivas')),
                ('tarifa_variable', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tarifa Coljuegos Variable (%)')),
                ('iva_presuntivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA Presuntivo ($)')),
                ('cobro_dias_no_transmitidos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cobro x Días NO Transmitido ($)')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro Activo')),
            ],
        ),
    ]
