# Generated by Django 4.2.4 on 2025-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0047_anoeconomico'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='porcentaje_pago',
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=5),
        ),
    ]
