# Generated by Django 3.2.8 on 2022-10-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentosLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion', models.FloatField(default=0, verbose_name='% Participación')),
                ('variable', models.FloatField(default=0, verbose_name='% variable')),
                ('diasintransmision', models.FloatField(default=0, verbose_name='Cobro * dia no transmitido')),
                ('valoriva', models.FloatField(default=0, verbose_name='$ Valor IVA')),
            ],
        ),
    ]
