# Generated by Django 3.2.8 on 2022-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentosliquidacion',
            name='año',
            field=models.CharField(default=2022, max_length=4, verbose_name='Año'),
        ),
    ]
