# Generated by Django 4.1.6 on 2023-06-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_descuentosliquidacion_año'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('idano', models.IntegerField(blank=True, default=0, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField(blank=True, default=0, null=True)),
                ('eliminar', models.IntegerField(blank=True, default=0, null=True)),
                ('idseguridad', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaseguridad', models.DateField(auto_now_add=True, null=True)),
                ('sincroniza', models.IntegerField(blank=True, default=0, null=True)),
                ('fechasincroniza', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
