# Generated by Django 3.2.8 on 2022-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.IntegerField(blank=True, default=0)),
                ('id_entrega', models.IntegerField(blank=True, default=0)),
                ('id_produccion', models.IntegerField(blank=True, default=0)),
                ('id_maquina', models.IntegerField(blank=True, default=0)),
                ('id_asignacion', models.IntegerField(blank=True, default=0)),
                ('id_despacho', models.IntegerField(blank=True, default=0)),
                ('id_status', models.IntegerField(blank=True, default=0)),
                ('serie_pmv', models.CharField(max_length=20)),
                ('serie_igg', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('fecha_produccion', models.DateField(auto_now_add=True)),
                ('eliminar', models.IntegerField(blank=True, default=0)),
                ('id_seguridad', models.IntegerField(blank=True, default=0)),
                ('fecha_seguridad', models.DateField(auto_now_add=True)),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('fecha_operacion', models.DateField(auto_now_add=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('id_entrega_serial', models.IntegerField(blank=True, default=0)),
                ('produccion_igg', models.DateField(auto_now_add=True)),
                ('fecha_codigos', models.DateField(auto_now_add=True)),
                ('id_cliente', models.IntegerField(blank=True, default=0)),
                ('id_sala', models.IntegerField(blank=True, default=0)),
                ('id_retiro', models.IntegerField(blank=True, default=0)),
                ('fecha_retiro', models.DateField(auto_now_add=True)),
                ('factura_pmv', models.CharField(max_length=15)),
            ],
        ),
    ]
