# Generated by Django 3.2.8 on 2022-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='id_status',
            field=models.IntegerField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('INSPIRED', 'Inspired'), ('REJECT', 'Reject'), ('SOLUCIONADA', 'Solucionada'), ('CERRADA', 'Cerrada')], default=0),
        ),
    ]
