# Generated by Django 3.2.8 on 2022-04-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0004_auto_20220309_1405'),
        ('Fallas_sporte', '0002_alter_falla_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha Programada'),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_final',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='id_falla',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='observacion',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='partes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
