# Generated by Django 3.2.8 on 2022-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0003_auto_20220429_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='id_status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('CERRADA', 'CERRADA')], max_length=50),
        ),
    ]
