# Generated by Django 3.2.8 on 2022-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0005_auto_20220506_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiones',
            name='id_status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ENVIADA', 'ENVIADA'), ('RECIBIDA', 'RECIBIDA'), ('CERRADA', 'CERRADA')], max_length=50),
        ),
    ]
