# Generated by Django 3.2.8 on 2022-05-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0002_statusasignacion'),
        ('Maestro', '0004_auto_20220309_1405'),
        ('Fallas_sporte', '0006_alter_remisiones_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiones',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='elaborado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha',
            field=models.DateField(verbose_name='Fecha Remision'),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_envio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_recibido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='guia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='id_transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.transporte'),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='observacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroserie', models.CharField(max_length=50)),
                ('descripcionpieza', models.CharField(max_length=100)),
                ('declaracion', models.CharField(max_length=50)),
                ('numeroreferencia', models.CharField(blank=True, max_length=50)),
                ('observacion', models.CharField(max_length=150)),
                ('codigomaquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
            ],
        ),
    ]
