# Generated by Django 3.2.8 on 2022-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0008_alter_serviciotecnico_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha',
            field=models.DateField(verbose_name='Fecha Programada'),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_final',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_visita',
            field=models.DateField(),
        ),
    ]
