# Generated by Django 3.2.8 on 2022-06-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0009_auto_20220523_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_final',
            field=models.DateField(null=True),
        ),
    ]
