# Generated by Django 3.2.8 on 2022-06-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0004_tipooperacion_nombrecorto'),
        ('Maestro', '0012_alter_cliente_emeailrecmaquina'),
        ('Fallas_sporte', '0010_alter_serviciotecnico_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='descripcion_igg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='falla',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='falla',
            name='email',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='falla',
            name='email_igg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='falla',
            name='email_igg2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_atencion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_escalado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_parcial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_reopen',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_seguridad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_sincroniza',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_solucion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='id_causa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.causasfalla'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='id_error',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.codigofalla'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='id_seguridad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='falla',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='falla',
            name='salas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='sincroniza',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='falla',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tecnico'),
        ),
    ]
