# Generated by Django 3.2.8 on 2022-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0011_auto_20220623_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_seguridad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
