# Generated by Django 3.2.8 on 2022-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0012_alter_falla_fecha_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_solucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
