# Generated by Django 3.2.8 on 2022-08-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0013_alter_falla_fecha_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_atencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_escalado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_parcial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_reopen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_sincroniza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
