# Generated by Django 3.2.8 on 2022-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0014_auto_20220811_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='id_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('INSPIRED', 'Inspired'), ('REJECT', 'Reject'), ('SOLUCIONADA', 'Solucionada'), ('CERRADA', 'Cerrada')], default=0, max_length=20),
        ),
    ]
