# Generated by Django 3.2.8 on 2022-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0015_alter_falla_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='atencion',
            field=models.CharField(choices=[('NIVEL 1 - TECNICO LOCAL DE SALA', 'NIVEL 1 - TECNICO LOCAL DE SALA'), ('NIVEL 2 - SOPORTE REMOTO', 'NIVEL 2 - SOPORTE REMOTO'), ('NIVEL 3 - TECNICO PMV ENVIADO', 'NIVEL 3 - TECNICO PMV ENVIADO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_escalado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_parcial',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_reopen',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_solucion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=50),
        ),
    ]
