# Generated by Django 3.2.8 on 2022-08-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0016_auto_20220811_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_solucion',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
    ]
