# Generated by Django 4.1.6 on 2023-02-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0012_solucionesfalla_statusfalla'),
        ('Maestro', '0039_alter_sala_modelo'),
        ('Fallas_sporte', '0017_auto_20220812_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_atencion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_cierre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_escalado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_parcial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_reopen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_solucion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='id_causa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.procedimientossfp'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusfalla'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='resuelto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.solucionesfalla'),
        ),
    ]
