# Generated by Django 4.1.6 on 2023-02-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0018_alter_falla_fecha_alter_falla_fecha_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_visita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='id_falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fallas_sporte.falla'),
        ),
    ]
