# Generated by Django 4.1.6 on 2023-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0019_alter_serviciotecnico_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiones',
            name='fecha',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_envio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_recibido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
