# Generated by Django 4.2.4 on 2023-10-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0012_solucionesfalla_statusfalla'),
        ('Fallas_sporte', '0020_alter_remisiones_fecha_alter_remisiones_fecha_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechanovedad', models.CharField(max_length=10, null=True)),
                ('observacion', models.CharField(max_length=150, null=True)),
                ('idfalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fallas_sporte.falla')),
                ('idtecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tecnico')),
            ],
        ),
    ]
