# Generated by Django 4.2.4 on 2023-10-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0013_statusserviciotecnico'),
        ('Fallas_sporte', '0021_novedadfalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusserviciotecnico'),
        ),
    ]
