# Generated by Django 4.2.4 on 2023-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0022_alter_serviciotecnico_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
