# Generated by Django 4.2.4 on 2023-10-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0039_alter_sala_modelo'),
        ('Fallas_sporte', '0023_alter_serviciotecnico_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemserviciotecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('repuesto', models.CharField(blank=True, max_length=150)),
                ('observacion', models.CharField(blank=True, max_length=150)),
                ('Sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
                ('maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
                ('serviciotecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fallas_sporte.serviciotecnico')),
            ],
        ),
    ]
