# Generated by Django 4.2.4 on 2023-10-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0025_alter_remisiones_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiones',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_recibido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
