# Generated by Django 4.2.4 on 2023-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0026_alter_remisiones_fecha_alter_remisiones_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
