# Generated by Django 4.2.4 on 2023-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0027_alter_falla_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falla',
            name='fecha_solucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
