# Generated by Django 4.2.4 on 2023-11-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0039_alter_sala_modelo'),
        ('Fallas_sporte', '0028_alter_falla_fecha_cierre_alter_falla_fecha_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='id_causa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.procedimientossfp'),
        ),
    ]
