# Generated by Django 4.2.4 on 2023-11-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0015_arquitectura'),
        ('Fallas_sporte', '0030_falla_arquitectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.status'),
        ),
    ]
