# Generated by Django 4.2.4 on 2024-01-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0015_arquitectura'),
        ('Fallas_sporte', '0031_falla_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='remision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fallas_sporte.remisiones'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.status'),
        ),
    ]
