# Generated by Django 4.2.4 on 2024-01-24 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0039_alter_sala_modelo'),
        ('Fallas_sporte', '0032_detalleremision_remision_alter_falla_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala'),
        ),
    ]
