# Generated by Django 4.2.4 on 2024-01-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0016_repuestos'),
        ('Fallas_sporte', '0033_detalleremision_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='fechadespacho',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='repuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.repuestos'),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='serialrepuestodespacho',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='serialrepuestoretorno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
