# Generated by Django 4.2.4 on 2024-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0034_detalleremision_fechadespacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='fecharetorno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
