# Generated by Django 4.2.4 on 2024-02-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0035_detalleremision_fecharetorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremision',
            name='declaracion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='descripcionpieza',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='fecharetorno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='numeroserie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='observacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='serialrepuestodespacho',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_envio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_recibido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
