# Generated by Django 4.2.4 on 2024-02-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0036_alter_detalleremision_declaracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='otro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
