# Generated by Django 4.2.4 on 2024-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0037_detalleremision_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='tipososporte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
