# Generated by Django 4.2.4 on 2024-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0038_falla_tipososporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiones',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_envio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_recibido',
            field=models.DateField(null=True),
        ),
    ]
