# Generated by Django 4.2.4 on 2024-07-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0039_alter_remisiones_fecha_alter_remisiones_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tipooperacion'),
        ),
    ]
