# Generated by Django 4.2.4 on 2024-08-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0046_alter_maquina_id_status'),
        ('Almacen', '0009_inventario_responsable'),
        ('Fallas_sporte', '0040_alter_falla_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='retornoremision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.retornoremision'),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='codigomaquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina'),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='fechadespacho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='remision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fallas_sporte.remisiones'),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala'),
        ),
    ]
