# Generated by Django 4.2.4 on 2024-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0041_detalleremision_retornoremision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremision',
            name='serialrepuestodespacho',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
