# Generated by Django 4.2.4 on 2024-09-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0012_eparacionremision_status'),
        ('Fallas_sporte', '0042_alter_detalleremision_serialrepuestodespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='remisionreparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.eparacionremision'),
        ),
    ]
