# Generated by Django 4.2.4 on 2024-09-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0020_estadoinventario_statusinventario_and_more'),
        ('Fallas_sporte', '0043_detalleremision_remisionreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.estadoinventario'),
        ),
    ]
