# Generated by Django 4.1.2 on 2022-12-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maestro', '0034_alter_maquina_tipo_operacion_and_more'),
        ('Anexos', '0010_statusretiro'),
        ('ProcesosIGG', '0016_alter_retiro_id_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrega_serial', models.IntegerField(blank=True, null=True)),
                ('id_inspired', models.CharField(max_length=15)),
                ('id_posicion', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('serie_igg', models.CharField(max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=150)),
                ('fecha_instalacion', models.DateField()),
                ('id_retiro', models.IntegerField(null=True)),
                ('fecha_retiro', models.DateField()),
                ('fecha_despacho', models.DateField()),
                ('eliminar', models.IntegerField(blank=True, default=0)),
                ('id_seguridad', models.IntegerField(blank=True, default=0)),
                ('fecha_seguridad', models.DateField(blank=True)),
                ('fecha_codigos', models.DateField(blank=True)),
                ('direccionn', models.CharField(max_length=50)),
                ('fecha_traslado', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_contrato', models.CharField(blank=True, max_length=20)),
                ('internet', models.IntegerField(blank=True)),
                ('ums', models.IntegerField(blank=True)),
                ('soporte', models.IntegerField(blank=True)),
                ('operacion', models.IntegerField(blank=True)),
                ('vendida', models.IntegerField(blank=True)),
                ('porcentaje', models.FloatField(blank=True)),
                ('liquida', models.IntegerField()),
                ('actualiza', models.IntegerField(blank=True)),
                ('garantia', models.IntegerField()),
                ('nuc', models.CharField(max_length=25)),
                ('resolucion', models.CharField(max_length=25)),
                ('despacho', models.IntegerField(blank=True)),
                ('tarifa', models.CharField(blank=True, max_length=25)),
                ('id_asignacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.asignacione')),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('id_sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
                ('id_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusasignacion')),
                ('menu_mix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.menu')),
                ('serie_pmv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
                ('tipo_operacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tipooperacion')),
            ],
        ),
    ]
