# Generated by Django 4.1.6 on 2023-07-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0012_solucionesfalla_statusfalla'),
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movasignacion',
            name='despacho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='direccionn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha_codigos',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha_despacho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha_seguridad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='fecha_traslado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='id_contrato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='id_retiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='id_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusasignacion'),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='internet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='operacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='porcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='serie_igg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='soporte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='tarifa',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='ums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movasignacion',
            name='vendida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
