# Generated by Django 4.2.4 on 2024-05-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0019_alter_razos_social_ciudad_cedula_and_more'),
        ('Movimientos', '0003_alter_movasignacion_actualiza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movasignacion',
            name='tipo_operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.status'),
        ),
    ]
