# Generated by Django 4.2.4 on 2024-05-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0004_alter_movasignacion_tipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movasignacion',
            name='razon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
    ]
