# Generated by Django 4.2.4 on 2024-05-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0005_movasignacion_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='movasignacion',
            name='diasliquida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movasignacion',
            name='fechaliquida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movasignacion',
            name='numeroresolucion',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movasignacion',
            name='produccionigg',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movasignacion',
            name='repcoljuegos',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
