# Generated by Django 4.2.4 on 2024-07-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0006_movasignacion_diasliquida_movasignacion_fechaliquida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movasignacion',
            name='tipo_operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tipooperacion'),
        ),
    ]
