# Generated by Django 4.2.4 on 2024-06-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='clientes',
        ),
    ]
