# Generated by Django 4.2.4 on 2024-06-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_remove_inventario_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.estadoinventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusinventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.repuestos'),
        ),
    ]
