# Generated by Django 4.2.4 on 2024-06-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fallas_sporte', '0039_alter_remisiones_fecha_alter_remisiones_fecha_envio_and_more'),
        ('Maestro', '0045_alter_maquina_razon'),
        ('Almacen', '0003_alter_inventario_estado_alter_inventario_id_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retornoremision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('fecha', models.DateField(null=True)),
                ('fecha_recibido', models.DateField(null=True)),
                ('contacto', models.CharField(max_length=50)),
                ('guia', models.CharField(blank=True, max_length=30)),
                ('elaborado', models.CharField(blank=True, max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('id_transporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.transporte')),
                ('remision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fallas_sporte.remisiones')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.repuestos')),
            ],
        ),
        migrations.CreateModel(
            name='eparacionremision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('fecha', models.DateField(null=True)),
                ('fecha_entrega_tecnico', models.DateField(null=True)),
                ('fecha_retorno_almacen', models.DateField(null=True)),
                ('elaborado', models.CharField(blank=True, max_length=50)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.repuestos')),
            ],
        ),
    ]
