# Generated by Django 4.2.4 on 2024-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_retornoremision_eparacionremision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracione',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
