# Generated by Django 4.2.4 on 2024-07-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0045_alter_maquina_razon'),
        ('Almacen', '0005_alter_declaracione_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='clientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
    ]
