# Generated by Django 4.2.4 on 2024-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0006_inventario_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
