# Generated by Django 4.2.4 on 2024-07-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0007_alter_inventario_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retornoremision',
            name='remision',
        ),
        migrations.AddField(
            model_name='retornoremision',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusremision'),
        ),
    ]
