# Generated by Django 4.2.4 on 2024-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0008_remove_retornoremision_remision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
