# Generated by Django 4.2.4 on 2024-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0009_inventario_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eparacionremision',
            name='tecnico',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
