# Generated by Django 4.2.4 on 2024-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0010_eparacionremision_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='eparacionremision',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
