# Generated by Django 4.2.4 on 2024-09-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0020_estadoinventario_statusinventario_and_more'),
        ('Almacen', '0011_eparacionremision_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='eparacionremision',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusremision'),
        ),
    ]
