# Generated by Django 4.2.4 on 2024-09-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0012_eparacionremision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracione',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='declaraciones/pdfs/'),
        ),
    ]
