# Generated by Django 4.2.4 on 2024-09-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0013_declaracione_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='declaracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.declaracione'),
        ),
    ]
