# Generated by Django 4.2.4 on 2025-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0014_inventario_declaracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='retornoremision',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
