# Generated by Django 4.2.4 on 2025-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0015_retornoremision_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eparacionremision',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
