from django.db import models
from Maestro.models import *
from Anexos.models import *
from Almacen.models import *
from .choices import *
# Create your models here.

class Falla(models.Model):
    salas = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True)
    #fecha_instalacion = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True, blank=True)
    id_error = models.ForeignKey(CodigoFalla, on_delete=models.CASCADE, null=True)
    id_causa = models.ForeignKey(ProcedimientosSFP, on_delete=models.CASCADE, null=True, blank=True)
    id_solucion = models.ForeignKey(SolucionFalla, on_delete=models.CASCADE, null=True, blank=True)
    numero = models.CharField(max_length=20, blank=True)
    reportado = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
    descripcion_igg = models.CharField(max_length=100, blank=True)
    apagada = models.IntegerField(default=0)
    fecha = models.DateField(null=True)
    fecha_solucion = models.DateField(null=True, blank=True)
    fecha_cierre = models.DateField(null=True, blank=True)
    id_status = models.ForeignKey(statusfalla, on_delete=models.CASCADE, null=True)
    observacion = models.CharField(max_length=100)
    eliminar = models.IntegerField(default=0, blank=True)
    email = models.IntegerField(default=0, blank=True)
    email_igg = models.IntegerField(default=0, blank=True)
    tecnico = models.ForeignKey(Tecnico, on_delete=models.CASCADE, null=True)
    id_seguridad = models.IntegerField(default=0, blank=True)
    fecha_seguridad = models.DateField(null=True, blank=True)
    sincroniza = models.IntegerField(default=0, blank=True)
    fecha_sincroniza = models.DateField(null=True, blank=True)
    telefono = models.CharField(max_length=50)
    prioridad = models.CharField(max_length=50, choices=prioridad)
    atencion = models.CharField(max_length=50, choices=atencion)
    resuelto = models.ForeignKey(solucionesfalla, on_delete=models.CASCADE, null=True)
    fecha_parcial = models.CharField(max_length=10, null=True, blank=True)
    juego = models.ForeignKey(Juego, on_delete=models.CASCADE, null=True, blank=True)
    fecha_atencion = models.CharField(max_length=10, null=True, blank=True)
    fecha_reopen = models.CharField(max_length=10, null=True, blank=True)
    fecha_escalado = models.CharField(max_length=10, null=True, blank=True)
    email_igg2 = models.IntegerField(default=0, blank=True)
    arquitectura = models.ForeignKey(arquitectura, on_delete=models.CASCADE, null=True, blank=True)
    operacion = models.ForeignKey(TipoOperacion, on_delete=models.CASCADE, null=True)
    tipososporte = models.CharField(max_length=10, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

class ServicioTecnico(models.Model):
    numero = models.CharField(max_length=20, blank=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    direccion = models.CharField(max_length=100, blank=True)
    descripcion = models.CharField(max_length=100)
    partes = models.CharField(max_length=100, blank=True)
    id_status = models.ForeignKey(statusserviciotecnico, on_delete=models.CASCADE, null=True)
    fecha = models.DateField(null=True)
    fecha_visita = models.DateField(null=True, blank=True)
    fecha_final = models.DateField(null=True, blank=True)
    observacion = models.CharField(max_length=100, blank=True)
    tecnico = models.ForeignKey(Tecnico, on_delete=models.CASCADE, null=True, blank=True)
    eliminar = models.IntegerField(default=0, blank=True)
    id_falla = models.ForeignKey(Falla, on_delete=models.CASCADE, null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

class itemserviciotecnico(models.Model):
    serviciotecnico = models.ForeignKey(ServicioTecnico, on_delete=models.CASCADE, null=True)
    maquina = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True)
    Sala = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True)
    fecha_visita = models.DateField(null=True, blank=True)
    fecha_cierre = models.DateField(null=True, blank=True)
    repuesto = models.CharField(max_length=150, blank=True)
    observacion = models.CharField(max_length=150, blank=True)

class Remisiones(models.Model):
    numero = models.CharField(max_length=20, blank=True)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)
    contacto = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=50, blank=True)
    id_status = models.ForeignKey(statusremision, on_delete=models.CASCADE, null=True)
    fecha = models.DateField(null=True)
    fecha_envio = models.DateField(null=True)
    fecha_recibido = models.DateField(null=True)
    guia = models.CharField(max_length=30, blank=True)
    id_transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True)
    observacion = models.CharField(max_length=100, blank=True)
    eliminar = models.IntegerField(default=0, blank=True)
    elaborado = models.CharField(max_length=50, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

class DetalleRemision(models.Model):
    remision =  models.ForeignKey(Remisiones, on_delete=models.CASCADE, null=True, blank=True)
    remisionreparacion = models.ForeignKey(eparacionremision, on_delete=models.CASCADE, null=True, blank=True)
    retornoremision = models.ForeignKey(Retornoremision, on_delete=models.CASCADE, null=True, blank=True)
    numeroserie = models.CharField(max_length=50, blank=True)
    descripcionpieza = models.CharField(max_length=100, blank=True)
    declaracion = models.CharField(max_length=50,blank=True)
    codigomaquina = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True, blank=True)
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE, null=True, blank=True)
    numeroreferencia = models.CharField(max_length=50, blank=True)
    observacion = models.CharField(max_length=150, blank=True)
    repuesto = models.ForeignKey(repuestos, on_delete=models.CASCADE, null=True)
    serialrepuestodespacho = models.CharField(max_length=100, blank=True)
    fechadespacho = models.CharField(max_length=10, null=True, blank=True)
    serialrepuestoretorno = models.CharField(max_length=100, blank=True)
    fecharetorno = models.CharField(max_length=10, null=True, blank=True)
    otro = models.CharField(max_length=50, null=True, blank=True)
    estado = models.ForeignKey(estadoinventario, on_delete=models.CASCADE, null=True, blank=True)

class Reparaciones(models.Model):
    numero = models.CharField(max_length=20)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    descripcion = models.CharField(max_length=100)
    id_status = models.CharField(max_length=50, choices=StatusSReparacion)
    fecha = models.DateTimeField()
    fecha_recibido = models.DateTimeField()
    fecha_final = models.DateTimeField()
    observacion = models.CharField(max_length=100)
    tecnico = models.ForeignKey(Tecnico, on_delete=models.CASCADE, null=True, blank=True)
    eliminar = models.IntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

class NovedadFalla(models.Model):
    idfalla = models.ForeignKey(Falla, on_delete=models.CASCADE, null=True)
    fechanovedad = models.CharField(max_length=10, null=True)
    idtecnico = models.ForeignKey(Tecnico, on_delete=models.CASCADE, null=True)
    observacion = models.CharField(max_length=150, null=True)
