# Generated by Django 3.2.8 on 2022-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0002_statusasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusasignacion',
            name='nombrecorto',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
