# Generated by Django 3.2.8 on 2022-07-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0004_tipooperacion_nombrecorto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razos_social',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='enviar_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='fecha_seguridad',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='fecha_sincroniza',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='id_seguridad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='sincroniza',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
