# Generated by Django 3.2.8 on 2022-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0005_auto_20220713_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='razos_social',
            name='clientes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
