# Generated by Django 3.2.8 on 2022-08-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0006_razos_social_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razos_social',
            name='corto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='fecha_seguridad',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='fecha_sincroniza',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
