# Generated by Django 4.2.4 on 2023-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0013_statusserviciotecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusremision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.IntegerField(default=1, null=True)),
                ('eliminar', models.IntegerField(default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
        ),
    ]
