# Generated by Django 4.2.4 on 2024-04-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0016_repuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razos_social',
            name='ciudad_cedula',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='ciudad_nit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
