# Generated by Django 4.2.4 on 2024-04-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0017_alter_razos_social_ciudad_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razos_social',
            name='create_at',
            field=models.CharField(max_length=50, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='fecha_seguridad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='fecha_sincroniza',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='razos_social',
            name='update_at',
            field=models.CharField(max_length=50, verbose_name='Editado'),
        ),
    ]
