# Generated by Django 4.2.4 on 2024-04-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0018_alter_razos_social_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razos_social',
            name='ciudad_nit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razos_social_nit', to='Anexos.ciudad'),
        ),
    ]
