# Generated by Django 4.2.4 on 2024-06-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0019_alter_razos_social_ciudad_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoinventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('activo', models.IntegerField(default=1, null=True)),
                ('eliminar', models.IntegerField(default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
        ),
        migrations.CreateModel(
            name='statusinventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('activo', models.IntegerField(default=1, null=True)),
                ('eliminar', models.IntegerField(default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
        ),

    ]
