# Generated by Django 3.2.8 on 2022-04-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0002_statusasignacion'),
        ('ProcesosIGG', '0002_asignacione_stado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacione',
            name='fecha',
            field=models.DateField(verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='numero',
            field=models.CharField(auto_created=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='stado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusasignacion', verbose_name='Estado'),
        ),
    ]
