# Generated by Django 3.2.8 on 2022-04-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0003_auto_20220419_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacione',
            name='numero',
        ),
    ]
