# Generated by Django 3.2.8 on 2022-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0004_remove_asignacione_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacione',
            name='fecha_codigos',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='fecha_instalacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='fecha_notificacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='fecha_revisado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
