# Generated by Django 3.2.8 on 2022-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0005_auto_20220426_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacione',
            name='modelo',
            field=models.CharField(choices=[('PA', 'SOLO PARTICIPACION'), ('OC', 'OC'), ('VP', 'VP'), ('VS', 'VS'), ('VF', 'VF'), ('AR', 'AR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='modelo',
            field=models.CharField(choices=[('PA', 'SOLO PARTICIPACION'), ('OC', 'OC'), ('VP', 'VP'), ('VS', 'VS'), ('VF', 'VF'), ('AR', 'AR')], max_length=80),
        ),
    ]
