# Generated by Django 3.2.8 on 2022-05-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0005_auto_20220516_1403'),
        ('ProcesosIGG', '0006_auto_20220516_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacione',
            name='modelo',
            field=models.CharField(choices=[('PA', 'PA'), ('OC', 'OC'), ('VP', 'VP'), ('VS', 'VS'), ('VF', 'VF'), ('AR', 'AR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='modelo',
            field=models.CharField(choices=[('PA', 'PA'), ('OC', 'OC'), ('VP', 'VP'), ('VS', 'VS'), ('VF', 'VF'), ('AR', 'AR')], max_length=80),
        ),
        migrations.CreateModel(
            name='Seriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.IntegerField(blank=True)),
                ('id_entrega', models.IntegerField(blank=True)),
                ('id_produccion', models.IntegerField(blank=True)),
                ('id_maquina', models.IntegerField(blank=True)),
                ('id_asignacion', models.IntegerField(blank=True)),
                ('id_despacho', models.IntegerField(blank=True)),
                ('id_status', models.IntegerField(blank=True)),
                ('serie_pmv', models.CharField(max_length=20)),
                ('serie_igg', models.CharField(max_length=20)),
                ('fecha', models.DateField(default=0)),
                ('fecha_entrega', models.DateField(default=0)),
                ('fecha_produccion', models.DateField(default=0)),
                ('eliminar', models.IntegerField(default=0)),
                ('ids_eguridad', models.IntegerField(default=0)),
                ('fecha_seguridad', models.DateField(default=0)),
                ('fecha_despacho', models.DateField(default=0)),
                ('fecha_operacion', models.DateField(default=0)),
                ('fecha_asignacion', models.DateField(default=0)),
                ('ide_ntrega_serial', models.IntegerField(blank=True)),
                ('fecha_codigos', models.DateField(default=0)),
                ('id_retiro', models.IntegerField(default=0)),
                ('fecha_retiro', models.DateField(default=0)),
                ('factura_pmv', models.CharField(blank=True, max_length=20)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('id_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
            ],
        ),
    ]
