# Generated by Django 3.2.8 on 2022-05-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0005_auto_20220516_1403'),
        ('ProcesosIGG', '0007_auto_20220519_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriales',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha',
            field=models.DateField(default=0, verbose_name='fecha asignacion'),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_codigos',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_despacho',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_entrega',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_operacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_produccion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_retiro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='fecha_seguridad',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='id_asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.asignacione'),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='id_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProcesosIGG.despacho'),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='id_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina'),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='id_retiro',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='ids_eguridad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='serie_igg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='seriales',
            name='serie_pmv',
            field=models.IntegerField(default=0),
        ),
    ]
