# Generated by Django 3.2.8 on 2022-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0008_auto_20220525_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='tipooperacion',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
