# Generated by Django 4.1.2 on 2022-10-29 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0008_tipomaquina'),
        ('ProcesosIGG', '0009_alter_instalacion_tipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_retiro',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='id_modelo_igg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.modelo'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='id_status',
            field=models.IntegerField(choices=[('DESPACHADO', 'D'), ('POR INSTALAR', 'P'), ('EN OPERACION', 'E'), ('UMS PROCESADO', 'U')], default=50),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='razon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
    ]
