# Generated by Django 4.1.2 on 2022-10-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0010_alter_instalacion_eliminar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_instalacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_retiro',
            field=models.DateField(blank=True, default=0),
        ),
    ]
