# Generated by Django 4.1.2 on 2022-10-29 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0033_auto_20221014_2155'),
        ('ProcesosIGG', '0011_alter_instalacion_fecha_instalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
    ]
