# Generated by Django 4.1.2 on 2022-10-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0009_statusinstalacion'),
        ('ProcesosIGG', '0012_alter_instalacion_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_retiro',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusinstalacion'),
        ),
    ]
