# Generated by Django 4.1.2 on 2022-11-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0009_statusinstalacion'),
        ('Maestro', '0033_auto_20221014_2155'),
        ('ProcesosIGG', '0013_alter_instalacion_fecha_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusinstalacion'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='id_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_notificacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_recibido',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_retiro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_traslado',
            field=models.DateField(),
        ),
    ]
