# Generated by Django 4.1.2 on 2022-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0014_instalacion_status_alter_instalacion_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='id_status',
            field=models.IntegerField(choices=[('SOLICITUD', 'SOLICITUD'), ('POR RETIRAR', 'POR RETIRAR'), ('RETIRADO', 'RETIRADO'), ('UMS PROCESADO', 'UMS PROCESADO')], default=50),
        ),
    ]
