# Generated by Django 4.1.2 on 2022-11-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0010_statusretiro'),
        ('ProcesosIGG', '0015_alter_retiro_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusretiro'),
        ),
    ]
