# Generated by Django 4.1.6 on 2023-05-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0016_alter_retiro_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='liquida',
            field=models.IntegerField(default=0),
        ),
    ]
