# Generated by Django 4.1.6 on 2023-05-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0017_instalacion_liquida'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='dialiquida',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
