# Generated by Django 4.1.6 on 2023-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0019_alter_retiro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fechaliquida',
            field=models.DateField(),
        ),
    ]
