# Generated by Django 4.2.4 on 2023-10-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0012_solucionesfalla_statusfalla'),
        ('ProcesosIGG', '0020_alter_instalacion_fecha_retiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='conductor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='contacto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_notificacion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_recibido',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_retiro',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_traslado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='guia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusretiro'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='notificacion',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='observacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='placa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='recibido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='tipo',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='ums_responsable',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
