# Generated by Django 4.2.4 on 2023-10-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0012_solucionesfalla_statusfalla'),
        ('Maestro', '0039_alter_sala_modelo'),
        ('ProcesosIGG', '0021_alter_retiro_cantidad_alter_retiro_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.statusretiro'),
        ),
        migrations.CreateModel(
            name='MovRetiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_retirada', models.PositiveIntegerField(default=1)),
                ('ums', models.CharField(blank=True, default=0, max_length=3, null=True)),
                ('fecha', models.CharField(max_length=10, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ProcesosIGG.retiro')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
            ],
        ),
    ]
