# Generated by Django 4.2.4 on 2024-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0022_alter_retiro_id_status_movretiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='fecha_retiro',
            field=models.DateField(),
        ),
    ]
