# Generated by Django 4.2.4 on 2024-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0023_alter_retiro_fecha_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movretiros',
            name='igg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movretiros',
            name='posicion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
