# Generated by Django 4.2.4 on 2024-04-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0024_movretiros_igg_movretiros_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='razon',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='razon',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
