# Generated by Django 4.2.4 on 2024-04-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0018_alter_razos_social_create_at_and_more'),
        ('ProcesosIGG', '0025_alter_contrato_razon_alter_instalacion_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='razon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='razon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social'),
        ),
    ]
