# Generated by Django 4.2.4 on 2024-04-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anexos', '0019_alter_razos_social_ciudad_cedula_and_more'),
        ('ProcesosIGG', '0026_alter_contrato_razon_alter_instalacion_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacione',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.status'),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='modelo',
            field=models.CharField(blank=True, choices=[('PA', 'PA'), ('OC', 'OC'), ('VP', 'VP'), ('VS', 'VS'), ('VF', 'VF'), ('AR', 'AR')], max_length=100, null=True),
        ),
    ]
