# Generated by Django 4.2.4 on 2024-04-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0027_asignacione_operacion_alter_asignacione_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacione',
            name='numero_seriales',
            field=models.IntegerField(default=0),
        ),
    ]
