# Generated by Django 4.2.4 on 2024-05-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0028_asignacione_numero_seriales'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacione',
            name='conductor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asignacione',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asignacione',
            name='guia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='asignacione',
            name='placa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='asignacione',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.transporte'),
        ),
    ]
