# Generated by Django 4.2.4 on 2024-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0029_asignacione_conductor_asignacione_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacione',
            name='fecha_despacho',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
