# Generated by Django 4.2.4 on 2024-05-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0030_asignacione_fecha_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='id_modelo_igg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.modelo'),
        ),
    ]
