# Generated by Django 4.2.4 on 2024-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesosIGG', '0031_alter_instalacion_id_modelo_igg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacione',
            name='fecha_instalacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacione',
            name='fecha_notificacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
